# Generated by Django 5.0.3 on 2024-04-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0006_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(default=None, upload_to='media/avatares/'),
        ),
    ]
