# Generated by Django 5.0.3 on 2024-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0007_estudiante_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/avatares/'),
        ),
    ]
