# Generated by Django 5.0.3 on 2024-04-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0008_alter_estudiante_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/avatares'),
        ),
    ]
