# Generated by Django 5.0.3 on 2024-04-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0009_alter_estudiante_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='avatar',
        ),
    ]
